networks:
  dmz_net:  # Réseau pour le serveur web et PHP
  db_net:   # Réseau pour PHP et la base de données

services:
  web:
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/var/www/html:ro
      - ./certificate/letsencrypt:/etc/letsencrypt
    container_name: web
    networks:
      - dmz_net

  php:
    build: php
    volumes:
      - ./html/www:/var/www/html/www
    container_name: php
    networks:
      - dmz_net
      - db_net
    env_file:
      - db.env

  mariadb:
    image: mariadb:11.1
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d/
      - ./conf/my-resolve.cnf:/etc/mysql/conf.d/my-resolve.cnf:ro
      - db_backup:/var/lib/mysql
    container_name: mariadb
    networks:
      - db_net
    env_file:
      - db/root.env

volumes:
  db_backup:
